// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using codebase_Assignment.Models;

#nullable disable

namespace codebase_Assignment.Migrations
{
    [DbContext(typeof(CodebaseContext))]
    [Migration("20251126085712_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("codebase_Assignment.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("house_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("codebase_Assignment.Models.OTP", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("is_created")
                        .HasColumnType("datetime2");

                    b.Property<string>("mobile_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("otp")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("OTP");
                });

            modelBuilder.Entity("codebase_Assignment.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("otp_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("otp_id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("codebase_Assignment.Models.UserPin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("UsersPin");
                });

            modelBuilder.Entity("codebase_Assignment.Models.Address", b =>
                {
                    b.HasOne("codebase_Assignment.Models.User", "user")
                        .WithOne("address")
                        .HasForeignKey("codebase_Assignment.Models.Address", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("codebase_Assignment.Models.User", b =>
                {
                    b.HasOne("codebase_Assignment.Models.OTP", "otp")
                        .WithOne("user")
                        .HasForeignKey("codebase_Assignment.Models.User", "otp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("otp");
                });

            modelBuilder.Entity("codebase_Assignment.Models.UserPin", b =>
                {
                    b.HasOne("codebase_Assignment.Models.User", "user")
                        .WithOne("userpin")
                        .HasForeignKey("codebase_Assignment.Models.UserPin", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("codebase_Assignment.Models.OTP", b =>
                {
                    b.Navigation("user")
                        .IsRequired();
                });

            modelBuilder.Entity("codebase_Assignment.Models.User", b =>
                {
                    b.Navigation("address")
                        .IsRequired();

                    b.Navigation("userpin")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
